=== arup-group/pam/src/pam/fixtures/dtd/objectattributes_v1.dtd
<?xml version="1.0" encoding="utf-8"?>

<!ELEMENT objectAttributes      (object)*>
<!-- this was originally "objectAttributes"-->

<!ELEMENT object (attribute)*>
<!ATTLIST object
          id        CDATA #REQUIRED>

<!ELEMENT attribute       (#PCDATA)>
<!ATTLIST attribute
          name        CDATA #REQUIRED
          class       CDATA #REQUIRED>

=== arup-group/pam/examples/data/londinium/attributes.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE objectAttributes SYSTEM "http://matsim.org/files/dtd/objectattributes_v1.dtd"><objectAttributes>
  <!--NTS london prelim 24nov2020 epsg27700-->
  <!--Created 2022-04-29 19:01:31.665639-->
  <object id="2_1_0">
    <attribute class="java.lang.String" name="SurveyYear">2002</attribute>
    <attribute class="java.lang.String" name="IndividualID">2</attribute>
    <attribute class="java.lang.String" name="HouseholdID">1</attribute>
    <attribute class="java.lang.String" name="PSUID">1</attribute>
    <attribute class="java.lang.String" name="VehicleID">2</attribute>
    <attribute class="java.lang.String" name="PersNo">2</attribute>
    <attribute class="java.lang.String" name="Age_B01ID">13</attribute>
    <attribute class="java.lang.String" name="OfPenAge_B01ID">2</attribute>
    <attribute class="java.lang.String" name="Sex_B01ID">1</attribute>
    <attribute class="java.lang.String" name="EdAttn1_B01ID">-10</attribute>
    <attribute class="java.lang.String" name="EdAttn2_B01ID">-10</attribute>
    <attribute class="java.lang.String" name="EdAttn3_B01ID">-10</attribute>
    <attribute class="java.lang.String" name="DrivLic_B02ID">1</attribute>
    <attribute class="java.lang.String" name="CarAccess_B01ID">2</attribute>
    <attribute class="java.lang.String" name="DrivDisable_B01ID">-9</attribute>
    <attribute class="java.lang.String" name="WkPlace_B01ID">1</attribute>
    <attribute class="java.lang.String" name="ES2000_B01ID">7</attribute>
    <attribute class="java.lang.String" name="NSSec_B03ID">3</attribute>
    <attribute class="java.lang.String" name="SC_B01ID">4</attribute>
    <attribute class="java.lang.String" name="Stat_B01ID">1</attribute>
    <attribute class="java.lang.String" name="SVise_B01ID">2</attribute>
    <attribute class="java.lang.String" name="EcoStat_B02ID">1</attribute>
    <attribute class="java.lang.String" name="PossHom_B01ID">2</attribute>
    <attribute class="java.lang.String" name="hid">1_1_0</attribute>
  </object>
  <object id="1_2_0">
    <attribute class="java.lang.String" name="SurveyYear">2002</attribute>
    <attribute class="java.lang.String" name="IndividualID">1</attribute>
    <attribute class="java.lang.String" name="HouseholdID">1</attribute>
    <attribute class="java.lang.String" name="PSUID">1</attribute>
    <attribute class="java.lang.String" name="VehicleID">1</attribute>
    <attribute class="java.lang.String" name="PersNo">1</attribute>
    <attribute class="java.lang.String" name="Age_B01ID">13</attribute>
    <attribute class="java.lang.String" name="OfPenAge_B01ID">2</attribute>
    <attribute class="java.lang.String" name="Sex_B01ID">2</attribute>
    <attribute class="java.lang.String" name="EdAttn1_B01ID">-10</attribute>
    <attribute class="java.lang.String" name="EdAttn2_B01ID">-10</attribute>
    <attribute class="java.lang.String" name="EdAttn3_B01ID">-10</attribute>
    <attribute class="java.lang.String" name="DrivLic_B02ID">1</attribute>
    <attribute class="java.lang.String" name="CarAccess_B01ID">2</attribute>
    <attribute class="java.lang.String" name="DrivDisable_B01ID">-9</attribute>
    <attribute class="java.lang.String" name="WkPlace_B01ID">1</attribute>
    <attribute class="java.lang.String" name="ES2000_B01ID">7</attribute>
    <attribute class="java.lang.String" name="NSSec_B03ID">2</attribute>
    <attribute class="java.lang.String" name="SC_B01ID">3</attribute>
    <attribute class="java.lang.String" name="Stat_B01ID">1</attribute>
    <attribute class="java.lang.String" name="SVise_B01ID">2</attribute>
    <attribute class="java.lang.String" name="EcoStat_B02ID">2</attribute>
    <attribute class="java.lang.String" name="PossHom_B01ID">2</attribute>
    <attribute class="java.lang.String" name="hid">1_2_0</attribute>
  </object>
  <object id="2_2_0">
    <attribute class="java.lang.String" name="SurveyYear">2002</attribute>
    <attribute class="java.lang.String" name="IndividualID">2</attribute>
    <attribute class="java.lang.String" name="HouseholdID">1</attribute>
    <attribute class="java.lang.String" name="PSUID">1</attribute>
    <attribute class="java.lang.String" name="VehicleID">2</attribute>
    <attribute class="java.lang.String" name="PersNo">2</attribute>
    <attribute class="java.lang.String" name="Age_B01ID">13</attribute>
    <attribute class="java.lang.String" name="OfPenAge_B01ID">2</attribute>
    <attribute class="java.lang.String" name="Sex_B01ID">1</attribute>
    <attribute class="java.lang.String" name="EdAttn1_B01ID">-10</attribute>
    <attribute class="java.lang.String" name="EdAttn2_B01ID">-10</attribute>
    <attribute class="java.lang.String" name="EdAttn3_B01ID">-10</attribute>
    <attribute class="java.lang.String" name="DrivLic_B02ID">1</attribute>
    <attribute class="java.lang.String" name="CarAccess_B01ID">2</attribute>
    <attribute class="java.lang.String" name="DrivDisable_B01ID">-9</attribute>
    <attribute class="java.lang.String" name="WkPlace_B01ID">1</attribute>
    <attribute class="java.lang.String" name="ES2000_B01ID">7</attribute>
    <attribute class="java.lang.String" name="NSSec_B03ID">3</attribute>
    <attribute class="java.lang.String" name="SC_B01ID">4</attribute>
    <attribute class="java.lang.String" name="Stat_B01ID">1</attribute>
    <attribute class="java.lang.String" name="SVise_B01ID">2</attribute>
    <attribute class="java.lang.String" name="EcoStat_B02ID">1</attribute>
    <attribute class="java.lang.String" name="PossHom_B01ID">2</attribute>
    <attribute class="java.lang.String" name="hid">1_2_0</attribute>
  </object>
  <object id="3_2_0">
    <attribute class="java.lang.String" name="SurveyYear">2002</attribute>
    <attribute class="java.lang.String" name="IndividualID">3</attribute>
    <attribute class="java.lang.String" name="HouseholdID">1</attribute>
    <attribute class="java.lang.String" name="PSUID">1</attribute>
    <attribute class="java.lang.String" name="VehicleID"> </attribute>
    <attribute class="java.lang.String" name="PersNo">3</attribute>
    <attribute class="java.lang.String" name="Age_B01ID">4</attribute>
    <attribute class="java.lang.String" name="OfPenAge_B01ID">2</attribute>
    <attribute class="java.lang.String" name="Sex_B01ID">1</attribute>
    <attribute class="java.lang.String" name="EdAttn1_B01ID">-10</attribute>
    <attribute class="java.lang.String" name="EdAttn2_B01ID">-10</attribute>
    <attribute class="java.lang.String" name="EdAttn3_B01ID">-10</attribute>
    <attribute class="java.lang.String" name="DrivLic_B02ID">-9</attribute>
    <attribute class="java.lang.String" name="CarAccess_B01ID">4</attribute>
    <attribute class="java.lang.String" name="DrivDisable_B01ID">-9</attribute>
    <attribute class="java.lang.String" name="WkPlace_B01ID">-9</attribute>
    <attribute class="java.lang.String" name="ES2000_B01ID">-9</attribute>
    <attribute class="java.lang.String" name="NSSec_B03ID">-9</attribute>
    <attribute class="java.lang.String" name="SC_B01ID">-9</attribute>
    <attribute class="java.lang.String" name="Stat_B01ID">-9</attribute>
    <attribute class="java.lang.String" name="SVise_B01ID">-9</attribute>
    <attribute class="java.lang.String" name="EcoStat_B02ID">-9</attribute>
    <attribute class="java.lang.String" name="PossHom_B01ID">-9</attribute>
    <attribute class="java.lang.String" name="hid">1_2_0</attribute>
  </object>
  <object id="4_2_0">
    <attribute class="java.lang.String" name="SurveyYear">2002</attribute>
    <attribute class="java.lang.String" name="IndividualID">4</attribute>
    <attribute class="java.lang.String" name="HouseholdID">1</attribute>
    <attribute class="java.lang.String" name="PSUID">1</attribute>
    <attribute class="java.lang.String" name="VehicleID"> </attribute>
    <attribute class="java.lang.String" name="PersNo">4</attribute>
    <attribute class="java.lang.String" name="Age_B01ID">2</attribute>
    <attribute class="java.lang.String" name="OfPenAge_B01ID">2</attribute>
    <attribute class="java.lang.String" name="Sex_B01ID">2</attribute>
    <attribute class="java.lang.String" name="EdAttn1_B01ID">-10</attribute>
    <attribute class="java.lang.String" name="EdAttn2_B01ID">-10</attribute>
    <attribute class="java.lang.String" name="EdAttn3_B01ID">-10</attribute>
    <attribute class="java.lang.String" name="DrivLic_B02ID">-9</attribute>
    <attribute class="java.lang.String" name="CarAccess_B01ID">4</attribute>
    <attribute class="java.lang.String" name="DrivDisable_B01ID">-9</attribute>
    <attribute class="java.lang.String" name="WkPlace_B01ID">-9</attribute>
    <attribute class="java.lang.String" name="ES2000_B01ID">-9</attribute>
    <attribute class="java.lang.String" name="NSSec_B03ID">-9</attribute>
    <attribute class="java.lang.String" name="SC_B01ID">-9</attribute>
    <attribute class="java.lang.String" name="Stat_B01ID">-9</attribute>
    <attribute class="java.lang.String" name="SVise_B01ID">-9</attribute>
    <attribute class="java.lang.String" name="EcoStat_B02ID">-9</attribute>
    <attribute class="java.lang.String" name="PossHom_B01ID">-9</attribute>
    <attribute class="java.lang.String" name="hid">1_2_0</attribute>
  </object>
  <object id="1_2_1">
    <attribute class="java.lang.String" name="SurveyYear">2002</attribute>
    <attribute class="java.lang.String" name="IndividualID">1</attribute>
    <attribute class="java.lang.String" name="HouseholdID">1</attribute>
    <attribute class="java.lang.String" name="PSUID">1</attribute>
    <attribute class="java.lang.String" name="VehicleID">1</attribute>
    <attribute class="java.lang.String" name="PersNo">1</attribute>
    <attribute class="java.lang.String" name="Age_B01ID">13</attribute>
    <attribute class="java.lang.String" name="OfPenAge_B01ID">2</attribute>
    <attribute class="java.lang.String" name="Sex_B01ID">2</attribute>
    <attribute class="java.lang.String" name="EdAttn1_B01ID">-10</attribute>
